### ISSUE TITLE
unable to run 'predict_with_padding' or tiling

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/core-bioimage-io-python#288] opened 2022-08-30 22:04 UTC
Hi @FynnBe @constantinpape @oeway 
I'm trying to use the library to load the 3D UNet of ZeroCost and predict a large volume with "predict_with_padding" but I got the following comment when trying to load the zip file:
```python
ValueError: ImageIO does not generally support reading folders. Limited support may be available via specific plugins. Specify the plugin explicitly using the `plugin` kwarg, e.g. `plugin='DICOM'`
```

**Comment by esgomezm** [comment] 2022-09-07 16:44
hi again, 

this is the error message I spoke about in the meeting. Additionally, I get this other error when trying to predict an image using the keras model:


```python
from bioimageio.core import load_resource_description
from bioimageio.core.prediction import predict_images, predict_with_padding


rdf_doi="/content/drive/MyDrive/cell-segmentation-from-membrane-staining-for-plant-tissues_keras_hdf5.zip" # the keras model downloaded from the bmz
model_resource =oad_resource_description(rdf_doi)

input_im_path = "/content/drive/MyDrive/N_405_A_ds2x.tif" # an Arabidopsis volume downloaded from their official repo
input_volume = io.imread(input_im_path)
input_volume = np.transpose(input_volume, [1,2,0])
input_volume = np.expand_dims(input_volume, [0, -1])

outputs = "/content/drive/MyDrive/arabidopsis/prediction.tiff"
predict_with_padding(model_resource, input_volume, outputs)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-26-e8f43c58fbf2>](https://localhost:8080/#) in <module>
     14 padding = {"x": 16, "y": 16, "z": 0, "mode": "dynamic"}
     15 predict_with_padding(
---> 16     model_resource, input_volume, outputs)
     17 

[/usr/local/lib/python3.7/site-packages/bioimageio/core/prediction.py](https://localhost:8080/#) in predict_with_padding(prediction_pipeline, inputs, padding, pad_right)
    197     if not padding:
    198         raise ValueError
--> 199     assert len(inputs) == len(prediction_pipeline.input_specs)
    200 
    201     output_spec = prediction_pipeline.output_specs[0]

AttributeError: 'Model' object has no attribute 'input_specs'
```

**Comment by constantinpape** [comment] 2022-09-07 18:50
Hi @esgomezm,
sorry I missed the first time you posted the issue.

For the first part: 

> I got the following comment when trying to load the zip file:

can you post a minimal example to reproduce this?


For the second part: `predict_with_padding` has to be called with a `prediction_pipeline` instead. If you change the code to
```
with bioimageio.core.create_prediction_pipeline(model_resource) as prediction_pipeline:
    predict_with_padding(model_resource, input_volume)
```
it should work. Also note that you need to cast the input_volume to an xarray.DataArray first.  (I will update the example notebook to explain this better.)


As a general comment:

> I'm trying to use the library to load the 3D UNet of ZeroCost and predict a large volume with

To achieve this (i.e. prediction with large volumes) `predict_with_tiling` is probably a better fit since you won't run out of (gpu) memory when the volume gets larger. (I will add something to the example notebook as well.)

**Comment by constantinpape** [comment] 2022-09-07 20:54
@esgomezm I have updated the usage notebook (https://github.com/bioimage-io/core-bioimage-io-python/blob/main/example/bioimageio-core-usage.ipynb) to better explain the prediction functionality, including `predict_with_padding` and `predict_with_tiling`.

**Comment by constantinpape** [comment] 2022-11-03 11:29
I am closing this now, feel free to reopen if the issue still persists @esgomezm.

**Closed** 2022-11-03 11:29 UTC
